function MultiInput1 = Import_Excel_File(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  MULTIINPUT1 = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  MULTIINPUT1 = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  MULTIINPUT1 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  MultiInput1 = importfile("C:\FK\2021_0316_YTW_beter_stitcher_pystripe_beta_v_1_02\Multi_Input.xlsx", "Sheet1", [2, 4]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Feb-2022 16:39:23

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 4];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 12);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":L" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Sorce_folder", "Working_folder", "channel_for_stitching", "making_shrink_after_stitching", "shrink_ratio", "max_cores", "inverting_x_y", "copy_data_to_working_drive", "recalculate_y_normalization", "hard_fix_empty_space", "z_truncate", "py_striping"];
opts.VariableTypes = ["string", "categorical", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Sorce_folder", "shrink_ratio"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Sorce_folder", "Working_folder", "shrink_ratio"], "EmptyFieldRule", "auto");

% Import the data
MultiInput1 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":L" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    MultiInput1 = [MultiInput1; tb]; %#ok<AGROW>
end

end