function MultiInput1 = Import_CSV_File(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MULTIINPUT1 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  MULTIINPUT1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  MultiInput1 = importfile("Z:\Labmembers\Fae\MyScripts\20220314_YTW_beter_stitcher_pystripe_beta_v_1_02_FK_multiStitcherUpdate - Copy\Multi_Input.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Mar-2022 14:48:42

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 15, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Sorce_folder", "Working_folder", "final_labdrive_location", "channel_for_stitching", "making_shrink_after_stitching", "shrink_ratio", "max_cores", "inverting_x_y", "copy_data_to_working_drive", "recalculate_y_normalization", "hard_fix_empty_space", "z_truncate", "py_striping", "magnification", "MaximumStepLength"];
opts.VariableTypes = ["string", "string", "string", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Sorce_folder", "Working_folder", "final_labdrive_location", "shrink_ratio", "magnification"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Sorce_folder", "Working_folder", "final_labdrive_location", "shrink_ratio", "magnification"], "EmptyFieldRule", "auto");
% opts = setvaropts(opts, "magnification", "TrimNonNumeric", false);
% opts = setvaropts(opts, "magnification", "ThousandsSeparator", ",");

% Import the data
MultiInput1 = readtable(filename, opts);

end